### ISSUE TITLE
[DISC] Question about API design with interior mutability

### ISSUE THREAD

**Issue by gezihuzi** [proxin187/Yaxi#6]
## Context

I noticed that some methods in the library are using &mut self despite having interior mutability (using Arc<Mutex<T>> or AtomicT). I'd like to understand the design decisions behind this choice and possibly suggest an alternative approach.

## Current Implementation

Currently, some methods require mutable references even though they use interior mutability internally:

```rust
pub struct Stream {
    reader: Arc<Mutex<dyn Streamable>>,
    writer: Arc<Mutex<dyn Streamable>>,
}
```

```rust
impl Stream {
    pub fn send(&mut self, request: &[u8]) -> Result<(), Error> {
        let mut lock = lock!(self.writer)?;

        lock.write_all(request)
            .map_err(|err| Error::Other { error: err.into() })
    }

    pub fn send_arr(&mut self, requests: &[Vec<u8>]) -> Result<(), Error> {
        let mut lock = lock!(self.writer)?;

        for request in requests {
            lock.write_all(request)
                .map_err(|err| Error::Other { error: err.into() })?;
        }

        Ok(())
    }
}
```

## Potential Alternative

Since interior mutability is already being used, these methods could potentially use &self instead:

```rust
impl Stream {
    pub fn send(&self, request: &[u8]) -> Result<(), Error> {
        let mut lock = lock!(self.writer)?;

        lock.write_all(request)
            .map_err(|err| Error::Other { error: err.into() })
    }

    pub fn send_arr(&self, requests: &[Vec<u8>]) -> Result<(), Error> {
        let mut lock = lock!(self.writer)?;

        for request in requests {
            lock.write_all(request)
                .map_err(|err| Error::Other { error: err.into() })?;
        }

        Ok(())
    }
}
```

## Benefits of using &self

1. More flexible API - allows multiple references to coexist
2. Better supports concurrent usage patterns
3. Follows the pattern seen in standard library types like Mutex and RwLock
4. Matches the interior mutability pattern's intended use case

## Questions

1. Was there a specific reason for choosing &mut self for these methods?
2. Are there any concerns about switching to &self that I might be missing?
3. Would you be open to changing these methods to use &self where interior mutability is already present?

## Related

Rust standard library's Mutex implementation: [std::sync::Mutex](https://doc.rust-lang.org/std/sync/struct.Mutex.html)
Similar pattern in RwLock: [std::sync::RwLock](https://doc.rust-lang.org/std/sync/struct.RwLock.html)

I'm happy to contribute a PR if this change makes sense for the project.

**Comment by proxin187** [comment]
Hi thank you so much for bringing this issue to my attention.

## Answers
1. No there wasn't a specific reason for choosing &mut self, the reason why these functions use &mut self is quite simply because i subconsciously just made them that way without thinking about it too much.
2.  As far as i'm aware there shouldn't be any issues with switching to &self, since it uses mutual exclusion it should be completely thread safe too.
3. Absolutely, i think the changes you have proposed are very rational.

## Conclusion
Ill convert all the functions that use interior mutability to use &self and close this issue once im done!

**Comment by proxin187** [comment]
Ill close this issue now as the public api has now been changed to use &self.

Thank you for your suggestion!
